version: "2"

services:

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  
  web:
    image: cnstntn/red-book-site
    hostname: redbooksite
    container_name: redbooksite
    ports:
      - "3005:3005"
    links:
      - mongo
    environment:
      - MONGO_URI=mongo
      - NODE_ENV=production
      - PORT=3005